### ISSUE TITLE
Docker Compose Stack?

### ISSUE THREAD

**Issue by pernak18** [earth-system-radiation/containers#4]
since we have multiple dependencies in the OS/compiler/netCDF/python stack, i'm wondering if we should codify with a `docker-compose` service stack that will do everything with a single build command given direction in a single YAML file as opposed to all of the separate builds we have listed in [`Readme.md`](https://github.com/earth-system-radiation/containers#docker-). something like:

```
docker-compose -f rte-rrtmgp-ci.yml build 
```

would build all images needed for the `rte-rrtmgp-ci:ifort` and `rte-rrtmgp-ci:nvfortran` end products

**Comment by RobertPincus** [comment]
That's an excellent idea.

**Comment by pernak18** [comment]
@RobertPincus this was completed and superficially documented in 1cff50c369ec8bd886a5b05fc4f3e13f403e922c
