### ISSUE TITLE
Automated Updates

### ISSUE THREAD

**Issue by pernak18** [earth-system-radiation/containers#5]
We'd like to automate our image builds when Intel and NVIDIA update the base images we use from them.

**Comment by pernak18** [comment]
for now, i'm doing this manually, and i noticed with NVIDIA that our `minimal-compiler:nvfortran` rebuilt:

```
docker pull nvcr.io/nvidia/nvhpc:21.2-devel-cuda_multi-ubuntu20.04
docker-compose -f rte-rrtmgp-ci.yml build min-nvfortran
```

but the derivative images just used what was in the cache, so i did:

```
docker-compose -f rte-rrtmgp-ci.yml build --no-cache min-nvfortran
docker-compose -f rte-rrtmgp-ci.yml build --no-cache nc-nvfortran
docker-compose -f rte-rrtmgp-ci.yml build --no-cache ci-nvfortran
```

**Comment by pernak18** [comment]
not sure how i could monitor their (NVIDIA's) image repository, but to automate this process maybe just run a `cron` job every day or week that removes `nvhpc` image and rebuilds our CI image from the ground up?

**Comment by RobertPincus** [comment]
Dunno that we need to monitor the Nvidia repo. I'd be happy enough with a setup that builds new Docker images and uploads them to Docker Hub every time we update the report with the Docker files in it.

**Comment by pernak18** [comment]
done with https://github.com/earth-system-radiation/containers/pull/6
