### ISSUE TITLE
CI/CD with GHCR

### ISSUE THREAD

**Issue by pernak18** [earth-system-radiation/containers#7]
similar to #5, but instead of pushing to DockerHub, push to GitHub Container Registry

**Comment by pernak18** [comment]
most of this functionality is in the [CI/CD configuration](https://github.com/earth-system-radiation/containers/blob/main/.github/workflows/github-actions.yaml), but i've commented out the push the GHCR because i was getting:

>   An image does not exist locally with the tag: ghcr.io/earth-system-radiation/rte-rrtmgp-ci

even though i did (successfully):

```
docker login ghcr.io -u pernak18 # use github TOKEN
docker tag earthsystemradiation/rte-rrtmgp-ci:ifort ghcr.io/earth-system-radiation/rte-rrtmgp-ci:ifort
docker push ghcr.io/earth-system-radiation/rte-rrtmgp-ci:ifort
docker tag earthsystemradiation/rte-rrtmgp-ci:nvfortran ghcr.io/earth-system-radiation/rte-rrtmgp-ci:nvfortran
docker push ghcr.io/earth-system-radiation/rte-rrtmgp-ci:nvfortran
```

**Comment by pernak18** [comment]
i believe this was address with b47469283ed4579f998bb02de9e792435efac21d

**Comment by pernak18** [comment]
reopening because CI tests [failed](https://github.com/earth-system-radiation/containers/actions/runs/3884887477)

**Comment by skosukhin** [comment]
I would like to ask you to try two things here:

1. @pernak18, please, apply the following patch to `main` and push to a **different** branch
    ```patch
    --- a/.github/workflows/github-actions.yaml
    +++ b/.github/workflows/github-actions.yaml
    @@ -33,14 +33,12 @@ jobs:
               tags: add-python:${{ matrix.compiler }}
    
           - name: Log in to Docker Hub
    -        if: ${{ github.ref == 'refs/heads/main' }}
             uses: docker/login-action@v2
             with:
               username: ${{ secrets.DOCKER_USERNAME }}
               password: ${{ secrets.DOCKER_PASSWORD }}
    
           - name: Log in to the Container registry
    -        if: ${{ github.ref == 'refs/heads/main' }}
             uses: docker/login-action@v2
             with:
               registry: ghcr.io
    @@ -52,7 +50,7 @@ jobs:
             with:
               file: Dockerfile-finalize
               build-args: COMPILER=${{ matrix.compiler }}
    -          push: ${{ github.ref == 'refs/heads/main' }}
    +          push: true
               tags: |
                 earthsystemradiation/rte-rrtmgp-ci:${{ matrix.compiler }}
    -            ghcr.io/earth-system-radiation/rte-rrtmgp-ci:${{ matrix.compiler }}
    +            ghcr.io/earth-system-radiation/containers/rte-rrtmgp-ci:${{ matrix.compiler }}
    ```
    I assume that this way GitHub might recognize that the image belongs to this repo and give you the same permissions as you have in the repo. Most probably, this will make the tag less "pretty" so I would personally prefer the second solution below but I'm curious to learn whether this works.
2. @RobertPincus could you, please, update the commit hash and force push to `main` (I know that this is something that should be avoided in general but I don't think it'll hurt much if you do it for this repo)? Something like `git commit --amend --no-edit && git push -f`. Once there is something in the registry, it should become possible to configure the images in the registry so that they can be updated by this project (and by all users who have write permissions for this project, not only you).

**Comment by pernak18** [comment]
@skosukhin you suggestion to me [worked](https://github.com/earth-system-radiation/containers/actions/runs/3886402683/jobs/6631463324)! thanks!

**Comment by skosukhin** [comment]
@pernak18 thanks for testing this. It turned out that `ghcr.io/earth-system-radiation/rte-rrtmgp-ci` already existed but was not configured to be editable with the actions of this repo. Things seem to work now. You can now remove `ci-edit` (and probably `cicd`).

**Comment by pernak18** [comment]
`ci-edit` and `cicd` are no more. long live `main`
